/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Quiz {
  'id' : bigint,
  'title' : string,
  'topic' : string,
  'questions' : Array<QuizQuestion>,
}
export interface QuizAttempt {
  'attemptId' : bigint,
  'score' : bigint,
  'timestamp' : bigint,
  'quizId' : bigint,
}
export interface QuizQuestion {
  'id' : bigint,
  'question' : string,
  'correctChoice' : bigint,
  'choices' : Array<string>,
}
export interface UserProfile {
  'name' : string,
  'rank' : [] | [string],
  'unit' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProgress' : ActorMethod<[], Array<QuizAttempt>>,
  'getQuiz' : ActorMethod<[bigint], Quiz>,
  'getQuizQuestions' : ActorMethod<[bigint], Array<QuizQuestion>>,
  'getQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuizAttempt' : ActorMethod<[bigint, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];