/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'rank' : IDL.Opt(IDL.Text),
  'unit' : IDL.Opt(IDL.Text),
});
export const QuizAttempt = IDL.Record({
  'attemptId' : IDL.Nat,
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
  'quizId' : IDL.Nat,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'correctChoice' : IDL.Nat,
  'choices' : IDL.Vec(IDL.Text),
});
export const Quiz = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'topic' : IDL.Text,
  'questions' : IDL.Vec(QuizQuestion),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProgress' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'getQuiz' : IDL.Func([IDL.Nat], [Quiz], ['query']),
  'getQuizQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(QuizQuestion)], ['query']),
  'getQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuizAttempt' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'rank' : IDL.Opt(IDL.Text),
    'unit' : IDL.Opt(IDL.Text),
  });
  const QuizAttempt = IDL.Record({
    'attemptId' : IDL.Nat,
    'score' : IDL.Nat,
    'timestamp' : IDL.Int,
    'quizId' : IDL.Nat,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'correctChoice' : IDL.Nat,
    'choices' : IDL.Vec(IDL.Text),
  });
  const Quiz = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'topic' : IDL.Text,
    'questions' : IDL.Vec(QuizQuestion),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProgress' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
    'getQuiz' : IDL.Func([IDL.Nat], [Quiz], ['query']),
    'getQuizQuestions' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(QuizQuestion)],
        ['query'],
      ),
    'getQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuizAttempt' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };